### PR TITLE
Add drag-and-drop + gallery fixes

### LINKED ISSUE #165: Allow drag-and-dropping images in gallery
You should be able to rearrange images in the gallery by dragging them around:

https://www.w3schools.com/HTML/html5_draganddrop.asp

### LINKED ISSUE #239: Gallery stuck open on mobile
On mobile, if a gallery image is close in aspect ratio to the viewport, it might be impossible to close the image if clicked on to enlarge, as clicking on the image doesn't close it and there's not enough space to click around it.

### PR DESCRIPTION
**Pull request by kjniemela**
closes #165, closes #239

Allow drag-and-dropping image in the gallery editor:
image

This works in mobile too. Also:

- Allow closing the gallery view by tapping on the image, preventing mobile users from getting stuck on the image preview.
- Allow uploading multiple images at once.

### CODE REVIEW

File: src/views/pages/item.ts [hunk 1]
```diff
@@ -67,9 +67,9 @@ export default {
     item.obj_data = JSON.parse(item.obj_data as string) as Record<string, any>;
     item.itemTypeName = ((universe.obj_data['cats'] ?? {})[item.item_type] ?? ['Missing Category'])[0];
     item.itemTypeColor = ((universe.obj_data['cats'] ?? {})[item.item_type] ?? [,,'#f3f3f3'])[2];
-    if (item.gallery && item.gallery.length > 0) {
-      item.gallery = item.gallery.sort((a, b) => a.id > b.id ? 1 : -1);
-    }
+    // if (item.gallery && item.gallery.length > 0) {
```
Comment (JoelNiemela) [inline src/views/pages/item.ts:70]: Should remove this code.

**Review by JoelNiemela — APPROVED** [review]

File: src/views/pages/item.ts (hunk 1 above)
Comment (kjniemela) [reply src/views/pages/item.ts:70]: Yep, good catch.
